// iconRegistry.ts
import {
    Setting,
    Grid2,
    StatusUp,
    Profile,
    EmojiHappy,
    ArrowUp,
    ArrowDown,
    ArrowCircleLeft2,
    ArrowCircleRight2,
    Ticket,
    GasStation,
    Heart,
    TaskSquare,
    Mobile,
    Category2,
    DocumentText,
    Calendar2,
    Element3,
    Global,
    DollarSquare,
    Sun1,
    Moon,
    Clock,
    LogoutCurve,
    Lock1,
    Notification,
    ArrowRight2,
    ArrowLeft2,
    Card
} from "iconsax-react-native";

export const iconRegistry = {
    EmojiHappy,
    grid: Grid2,
    "status up": StatusUp,
    setting: Setting,
    profile: Profile,
    "arrow up": ArrowUp,
    "arrow down": ArrowDown,
    "arrow left": ArrowCircleLeft2,
    "arrow right": ArrowCircleRight2,
    ticket: Ticket,
    "gas station": GasStation,
    heart: Heart,
    element3: Element3,
    mobile: Mobile,
    task: TaskSquare,
    category: Category2,
    "document text": DocumentText,
    calender: Calendar2,
    global: Global,
    dollar: DollarSquare,
    moon: Moon,
    sun: Sun1,
    clock: Clock,
    logout: LogoutCurve,
    lock: Lock1,
    notification: Notification,
    chevronRight: ArrowRight2,
    chevronLeft: ArrowLeft2,
    card: Card
} as const;

export type TIconsaxName = keyof typeof iconRegistry;